### ISSUE TITLE
Write a road map

### ISSUE THREAD

**Issue by apt1002** [apt1002/fvq#4]
Requested by @rrthomas and a good idea.

**Comment by apt1002** [comment]
This is as good a place as any. In no particular order, here are some things I would like to do eventually:

- [ ] Generalise beyond greyscale images:
  - [ ] Add an axis to every image transform to represent the colour channel index (#1).
  - [ ] Convert to an internal colour space similar to LUV.
  - [ ] Maybe predict U and V based on L.
  - [ ] Generalise the perceptual model to estimate colour discrimination ellipsoids.
  - [ ] Generalise the quantizer. Probably just loop over the colour channels.
  - [ ] Same tasks for the alpha channel.

- [ ] Work on the tree quantizer:
  - [ ] Abstract over the perceptual model, to get it out of the way and prevent bugs.
  - [ ] Choose a codebook (a finite set of common nearly blank image tiles), and make each leaf of the quantized tree be one of these tiles.
  - [ ] Write `Tree::arrow()` analogous to `ShiftedBCC::arrow()`:
    - [ ] Write an `arrow()` function for codewords.
    - [ ] Define how non-leaf trees map onto leaf trees.
    - [ ] Work out the nearest-neighbour algorithm.
  - [ ] Define a probability model over trees.
  - [ ] Modify the nearest-neighbour algorithm to balance quantization error with file size.
  - [ ] Write an iterative algorithm to train the codebook on a corpus of images.

- [ ] Write an arithmetic encoder (probably not worth adding a third-party dependency):
  - [ ] Interface it with the tree quantizer.

- [ ] Define the FVQ file format.
  - [ ] Header:
    - [ ] Version
    - [ ] has_colour
    - [ ] has_alpha
    - [ ] Original resolution
    - [ ] Quality
  - [ ] Container format.

- [ ] Optimization:
  - [ ] SIMD
  - [ ] Threads
  - [ ] Hand-compile some of the overly abstract parts.
